In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [40]:
df = pd.read_csv('happiness_score_dataset.csv')
df.head()

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  Dystopia Residual  
0     0.29678            2.51738  
1     0.43630            2.70201  
2     0.34139            2.49204  
3     0.34699            2.46531  
4     0.45811            2.45176

In [41]:
X = df.drop(['Country','Region', 'Happiness Rank', 'Happiness Score','Dystopia Residual'], axis=1)

y = df['Happiness Score']

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)


Mean Squared Error: 0.23863419471668829


In [45]:
new_country = np.array([[0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678]])
new_country
res = model.predict(new_country)

In [46]:
res

array([6.74750529])

In [47]:
new_country = np.array([[0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139]])
new_country
res = model.predict(new_country)
res

array([6.71662423])

In [ ]:
# Using another regressor to find better results

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Load the dataset
data = pd.read_csv('happiness_score_dataset.csv')

# Define the predictors and the target variable
X = data.drop(['Country','Region', 'Happiness Rank', 'Happiness Score','Dystopia Residual'], axis=1)
y = data['Happiness Score']

# Split the dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest Regressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Calculate the mean squared error of the predictions
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

Mean Squared Error: 0.27681335503437515


In [50]:
new_country = np.array([[0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139]])
new_country
res = model.predict(new_country)
res

/Users/deepika/Documents/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([7.46272])

In [ ]:
# This value is much closer to the actual value although the MSE value is greater. Further tests can help us decide which model is better i.e., Linear Regression or Random Forest.